version: "3.7"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/pi/Docker/portainer/data:/data

  homeassistant:
    container_name: homeassistant
    # image: homeassistant/raspberrypi4-homeassistant:stable
    build: ../homeassistant/docker
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/pi/Docker/homeassistant/config:/config"    
      - "/home/pi/Docker/homeassistant/media:/media"
      - "/home/pi/Docker/homeassistant/config/www:/media/www"
    restart: unless-stopped
    privileged: true
    network_mode: host
    #devices:
      #- "/dev/snd"

  esphome:
    container_name: esphome
    image: esphome/esphome
    volumes:
      - /home/pi/Docker/homeassistant/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host
